-- VitaWeave 2.0 Database Schema

-- Users Table (Profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'ASHA',
  ward TEXT,
  language TEXT DEFAULT 'English',
  avatar_url TEXT,
  level INTEGER DEFAULT 1,
  lives_impacted INTEGER DEFAULT 0,
  alerts_sent INTEGER DEFAULT 0,
  campaigns_led INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Patients Table
CREATE TABLE IF NOT EXISTS public.patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER,
  condition TEXT,
  last_visit DATE DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'Stable',
  risk_level TEXT DEFAULT 'Low', -- 'High', 'Medium', 'Low'
  phone TEXT,
  image_url TEXT,
  follow_up_due TEXT,
  follow_up_urgent BOOLEAN DEFAULT FALSE,
  asha_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Community Alerts
CREATE TABLE IF NOT EXISTS public.community_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  severity TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  date DATE DEFAULT CURRENT_DATE,
  icon TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pharmacy Trends
CREATE TABLE IF NOT EXISTS public.pharmacy_trends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medicine TEXT NOT NULL,
  count INTEGER DEFAULT 0,
  max_count INTEGER DEFAULT 200,
  trend TEXT DEFAULT 'stable', -- 'up', 'down', 'stable'
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Symptom Reports
CREATE TABLE IF NOT EXISTS public.symptom_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symptom TEXT NOT NULL,
  count INTEGER DEFAULT 0,
  trend TEXT DEFAULT 'stable',
  ward TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Weekly Trends (Aggregated stats)
CREATE TABLE IF NOT EXISTS public.weekly_trends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day TEXT NOT NULL, -- 'Mon', 'Tue', etc.
  value INTEGER DEFAULT 0,
  max_value INTEGER DEFAULT 40,
  week_start_date DATE DEFAULT CURRENT_DATE
);

-- AI Insights
CREATE TABLE IF NOT EXISTS public.ai_insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon TEXT,
  title TEXT NOT NULL,
  description TEXT,
  severity TEXT DEFAULT 'info',
  action_label TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Dashboard Tasks
CREATE TABLE IF NOT EXISTS public.dashboard_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  priority TEXT DEFAULT 'routine', -- 'urgent', 'today', 'routine'
  icon TEXT,
  asha_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Weekly Alerts (Personal alerts for ASHA)
CREATE TABLE IF NOT EXISTS public.weekly_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  time_ago TEXT,
  severity TEXT DEFAULT 'Medium',
  asha_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS) Basic Setup
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_alerts ENABLE ROW LEVEL SECURITY;

-- Policies (Simplified for development)
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can see patients." ON public.patients FOR SELECT USING (true); -- Usually restricted to asha_id
CREATE POLICY "Public community alerts are viewable." ON public.community_alerts FOR SELECT USING (true);
CREATE POLICY "Public trends are viewable." ON public.pharmacy_trends FOR SELECT USING (true);
CREATE POLICY "Public symptom reports are viewable." ON public.symptom_reports FOR SELECT USING (true);
CREATE POLICY "Public weekly trends are viewable." ON public.weekly_trends FOR SELECT USING (true);
CREATE POLICY "Public AI insights are viewable." ON public.ai_insights FOR SELECT USING (true);
